export const FETCHING_NEARBY_LOCATIONS = 'FETCHING_NEARBY_LOCATIONS';
export const FETCHING_LOCATIONS_SUCCESS = 'FETCHING_LOCATIONS_SUCCESS';
export const FETCHING_LOCATIONS_FAILURE = 'FETCHING_LOCATIONS_FAILURE';

export const FETCHING_USER_LOCATION = 'FETCHING_USER_LOCATION';
export const FETCHING_USER_LOCATION_SUCCESS = 'FETCHING_USER_LOCATION_SUCCESS';
export const FETCHING_USER_LOCATION_FAILURE = 'FETCHING_USER_LOCATION_FAILURE';

export const FETCHING_DISTANCES = 'FETCHING_DISTANCES';
export const FETCHING_DISTANCES_SUCCESS = 'FETCHING_DISTANCES_SUCCESS';
export const FETCHING_DISTANCES_FAILURE = 'FETCHING_DISTANCES_FAILURE';

export const FETCHING_ROUTE = 'FETCHING_ROUTE';
export const FETCHING_ROUTE_SUCCESS = 'FETCHING_ROUTE_SUCCESS';
export const FETCHING_ROUTE_FAILURE = 'FETCHING_ROUTE_FAILURE';

export const INCREASE_AREA='INCREASE_AREA';
export const DECREASE_AREA='DECREASE_AREA';
export const REGION='REGION';
export const UPDATED_REGION='UPDATED_REGION';
